services:
  db:
    image: mysql:8.4
    container_name: hostedftp-db
    env_file:
      - .env                 
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
      - ../sql-scripts:/docker-entrypoint-initdb.d:ro
    ports: ["3306:3306"]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 3s
      retries: 20

  app:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    env_file: [.env]
    environment:
      DB_URL: ${DB_URL}
      DB_HOST: ${DB_HOST}
      DB_PORT: "${DB_PORT}"
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
    ports: ["8080:8080"]

volumes:
  dbdata:
