CREATE DATABASE IF NOT EXISTS hostedftp
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE hostedftp;

DROP TABLE IF EXISTS users;
CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username   VARCHAR(50)  NOT NULL UNIQUE,
  password   VARCHAR(255) NOT NULL
);

